/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthImagesIndexRouteImport } from './routes/_auth/images/index'
import { Route as AuthCategoriesIndexRouteImport } from './routes/_auth/categories/index'
import { Route as AuthImagesUploadRouteImport } from './routes/_auth/images/upload'
import { Route as AuthImagesImageIdRouteImport } from './routes/_auth/images/$imageId'
import { Route as AuthCategoriesPreviewRouteImport } from './routes/_auth/categories/preview'
import { Route as AuthCategoriesOrderRouteImport } from './routes/_auth/categories/order'
import { Route as AuthCategoriesNewRouteImport } from './routes/_auth/categories/new'
import { Route as AuthCategoriesCategoryIdRouteImport } from './routes/_auth/categories/$categoryId'
import { Route as AuthCategoriesCategoryIdProjectOrderRouteImport } from './routes/_auth/categories/$categoryId_.project-order'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImagesIndexRoute = AuthImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesIndexRoute = AuthCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImagesUploadRoute = AuthImagesUploadRouteImport.update({
  id: '/images/upload',
  path: '/images/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImagesImageIdRoute = AuthImagesImageIdRouteImport.update({
  id: '/images/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesPreviewRoute = AuthCategoriesPreviewRouteImport.update({
  id: '/categories/preview',
  path: '/categories/preview',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesOrderRoute = AuthCategoriesOrderRouteImport.update({
  id: '/categories/order',
  path: '/categories/order',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesNewRoute = AuthCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesCategoryIdRoute =
  AuthCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCategoriesCategoryIdProjectOrderRoute =
  AuthCategoriesCategoryIdProjectOrderRouteImport.update({
    id: '/categories/$categoryId_/project-order',
    path: '/categories/$categoryId/project-order',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/categories/$categoryId': typeof AuthCategoriesCategoryIdRoute
  '/categories/new': typeof AuthCategoriesNewRoute
  '/categories/order': typeof AuthCategoriesOrderRoute
  '/categories/preview': typeof AuthCategoriesPreviewRoute
  '/images/$imageId': typeof AuthImagesImageIdRoute
  '/images/upload': typeof AuthImagesUploadRoute
  '/categories/': typeof AuthCategoriesIndexRoute
  '/images/': typeof AuthImagesIndexRoute
  '/categories/$categoryId/project-order': typeof AuthCategoriesCategoryIdProjectOrderRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof AuthIndexRoute
  '/categories/$categoryId': typeof AuthCategoriesCategoryIdRoute
  '/categories/new': typeof AuthCategoriesNewRoute
  '/categories/order': typeof AuthCategoriesOrderRoute
  '/categories/preview': typeof AuthCategoriesPreviewRoute
  '/images/$imageId': typeof AuthImagesImageIdRoute
  '/images/upload': typeof AuthImagesUploadRoute
  '/categories': typeof AuthCategoriesIndexRoute
  '/images': typeof AuthImagesIndexRoute
  '/categories/$categoryId/project-order': typeof AuthCategoriesCategoryIdProjectOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/categories/$categoryId': typeof AuthCategoriesCategoryIdRoute
  '/_auth/categories/new': typeof AuthCategoriesNewRoute
  '/_auth/categories/order': typeof AuthCategoriesOrderRoute
  '/_auth/categories/preview': typeof AuthCategoriesPreviewRoute
  '/_auth/images/$imageId': typeof AuthImagesImageIdRoute
  '/_auth/images/upload': typeof AuthImagesUploadRoute
  '/_auth/categories/': typeof AuthCategoriesIndexRoute
  '/_auth/images/': typeof AuthImagesIndexRoute
  '/_auth/categories/$categoryId_/project-order': typeof AuthCategoriesCategoryIdProjectOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/unauthorized'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/categories/order'
    | '/categories/preview'
    | '/images/$imageId'
    | '/images/upload'
    | '/categories/'
    | '/images/'
    | '/categories/$categoryId/project-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/unauthorized'
    | '/'
    | '/categories/$categoryId'
    | '/categories/new'
    | '/categories/order'
    | '/categories/preview'
    | '/images/$imageId'
    | '/images/upload'
    | '/categories'
    | '/images'
    | '/categories/$categoryId/project-order'
  id:
    | '__root__'
    | '/_auth'
    | '/sign-in'
    | '/unauthorized'
    | '/_auth/'
    | '/_auth/categories/$categoryId'
    | '/_auth/categories/new'
    | '/_auth/categories/order'
    | '/_auth/categories/preview'
    | '/_auth/images/$imageId'
    | '/_auth/images/upload'
    | '/_auth/categories/'
    | '/_auth/images/'
    | '/_auth/categories/$categoryId_/project-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/images/': {
      id: '/_auth/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof AuthImagesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/': {
      id: '/_auth/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthCategoriesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/images/upload': {
      id: '/_auth/images/upload'
      path: '/images/upload'
      fullPath: '/images/upload'
      preLoaderRoute: typeof AuthImagesUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/images/$imageId': {
      id: '/_auth/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof AuthImagesImageIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/preview': {
      id: '/_auth/categories/preview'
      path: '/categories/preview'
      fullPath: '/categories/preview'
      preLoaderRoute: typeof AuthCategoriesPreviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/order': {
      id: '/_auth/categories/order'
      path: '/categories/order'
      fullPath: '/categories/order'
      preLoaderRoute: typeof AuthCategoriesOrderRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/new': {
      id: '/_auth/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof AuthCategoriesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/$categoryId': {
      id: '/_auth/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AuthCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories/$categoryId_/project-order': {
      id: '/_auth/categories/$categoryId_/project-order'
      path: '/categories/$categoryId/project-order'
      fullPath: '/categories/$categoryId/project-order'
      preLoaderRoute: typeof AuthCategoriesCategoryIdProjectOrderRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthCategoriesCategoryIdRoute: typeof AuthCategoriesCategoryIdRoute
  AuthCategoriesNewRoute: typeof AuthCategoriesNewRoute
  AuthCategoriesOrderRoute: typeof AuthCategoriesOrderRoute
  AuthCategoriesPreviewRoute: typeof AuthCategoriesPreviewRoute
  AuthImagesImageIdRoute: typeof AuthImagesImageIdRoute
  AuthImagesUploadRoute: typeof AuthImagesUploadRoute
  AuthCategoriesIndexRoute: typeof AuthCategoriesIndexRoute
  AuthImagesIndexRoute: typeof AuthImagesIndexRoute
  AuthCategoriesCategoryIdProjectOrderRoute: typeof AuthCategoriesCategoryIdProjectOrderRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthCategoriesCategoryIdRoute: AuthCategoriesCategoryIdRoute,
  AuthCategoriesNewRoute: AuthCategoriesNewRoute,
  AuthCategoriesOrderRoute: AuthCategoriesOrderRoute,
  AuthCategoriesPreviewRoute: AuthCategoriesPreviewRoute,
  AuthImagesImageIdRoute: AuthImagesImageIdRoute,
  AuthImagesUploadRoute: AuthImagesUploadRoute,
  AuthCategoriesIndexRoute: AuthCategoriesIndexRoute,
  AuthImagesIndexRoute: AuthImagesIndexRoute,
  AuthCategoriesCategoryIdProjectOrderRoute:
    AuthCategoriesCategoryIdProjectOrderRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
